version: '3'


vars:
    PACKAGE_MANAGER: pnpm


dotenv: ["./environment/.front-end.env"]


tasks:
    dependencies:
        cmds:
            - "{{ .PACKAGE_MANAGER }} install"

    run:
        deps: [dependencies]
        cmds:
            - "{{ .PACKAGE_MANAGER }} run dev"